# Copyright 2021 Clivern
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Ensure Redis is Installed
  apt:
    name: redis-server
    state: present
  tags: [ redis ]

- name: Ensure Redis is Started
  service:
    name: redis-server
    state: started
    enabled: yes
  tags: [ redis ]

- name: Enable Password Authentication for Redis
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: "^# requirepass"
    line: "requirepass {{ redis_password }}"
    state: present
    backup: yes
  notify: restart redis
  tags: [ redis ]

- name: Run Redis from Systemd
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: "^supervised no"
    line: "supervised systemd"
    state: present
    backup: yes
  notify: restart redis
  tags: [ redis ]
